eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8080/eureka
logging:
    file:
        name: ./log/customer-service.log
    level:
        org:
            hibernate:
                SQL: DEBUG
                type: TRACE
        root: INFO
server:
    port: 8082
spring:
    application:
        name: customer-service
    datasource:
        password: mysqlpw
        url: jdbc:mysql://localhost:49164/customer_service?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
    jackson:
        serialization:
            indent_output: true
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show:
            sql: true
springdoc:
    api-docs:
        path: /api-docs

uri:
    credit-score-service : http://localhost:8081/credit-score-service/credit-score