logging:
  file:
    name: ./log/customer.log
  level:
    root: info
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8082

spring:
  cloud:
    config:
      enabled: false
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: customer-service
  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include:*

